### ISSUE TITLE
Idea: simple setup option using query string

### ISSUE THREAD

**Issue by fabianmichael** [bnomei/kirby3-fingerprint#1]
First of all: Congrats to already having a public Kirby 3 plugin on GitHub! :-D

I recently had a discussion with a fellow developer whether it is really worth the hassle of changing your server configuration (ngninx conf or .htaccess) for rewriting file names of assets. Okay, let’s be fair, it is just a matter of seconds. But it always involves an additional setup step and is not exactly beginner-friendly.

For a quick setup and testing puropses, it is often much simpler to just use a simple query string for cache-busting (e.g. `stylo.css?v=1928356`). I would recommend to add this and maybe even use it as the default behavior. It makes a one-click install of the plugin possible and also makes it more beginner-friendly. Advanced users wo need to do some setup anyway for changing the rewrite config could then just activate the behavior in their config file. That way, the default behavior of the plugin would not break loading of assets when the rewrite rule is inactive (e.g. after moving to another server).

What do you think?

**Comment by bnomei** [comment]
great idea. done. https://github.com/bnomei/kirby3-fingerprint/commit/a255e5e2ded929ed05dedac3d49636c9fa2a0193

**Comment by bvdputte** [comment]
Using query strings for cache busting is considered an anti-pattern as it can cause caching issues in CDN's or proxy's (such as squid).

More info: 
https://www.stevesouders.com/blog/2008/08/23/revving-filenames-dont-use-querystring/
or more recent:
https://www.keycdn.com/support/remove-query-strings-from-static-resources/

IMHO it's worth the little work of adding an exception to your mod rewrite in .htaccess.

**Comment by S1SYPHOS** [comment]
It'd be great to see an example of your solution, @bvdputte?

**Comment by bvdputte** [comment]
@S1SYPHOS , I use this: https://github.com/bvdputte/kirby-fingerprint 

It's basically the default `js()` and `css()` helpers, but with fingerprinting added.  It's not as feature-rich as bnomei's plugin; but is enough for my use case.

**Comment by S1SYPHOS** [comment]
I see. For local files, there's not much of a point adding SRI, anyway ..
