### ISSUE TITLE
Echo only URL of the file with fingerprint

### ISSUE THREAD

**Issue by lareusmedia** [bnomei/kirby3-fingerprint#12]
Hi,

im testing your plugin and it works fine, but i have one problem currently:

In the header i use:
`<?= Bnomei\Fingerprint::css('/assets/css/main.min.css') ?>`
which creates
`<link href="http:/www.mydomain.test/assets/css/main.min.css?v=1575271772" rel="stylesheet">`

But i am trying to preload the CSS file with
`<link rel="preload" href="<?= url('/assets/css/main.min.css') ?>" as="style">`
which leads to an waring in chrome because the version is missing...

How can i echo just the URL of my css file with your plugin including the version number?

**Comment by bnomei** [comment]
yes the readme was confusing in that regard. i added a new helper for the raw url as `Fingerprint::url()` and updated the readme.

```php
echo Bnomei\Fingerprint::css('/assets/css/index.css');
// <style> element with https://../assets/css/index.css?v=1203291283

echo Bnomei\Fingerprint::js('/assets/js/index.min.js');
// <link> element https://../assets/js/index.min.js?v=1203291283

echo Bnomei\Fingerprint::url('/assets/css/index.css');
// raw url https://../assets/css/index.css?v=1203291283
```

**Comment by bnomei** [comment]
<link rel="preload" href="<?= Bnomei\Fingerprint::url('/assets/css/main.min.css') ?>" as="style">

**Comment by bnomei** [comment]
https://github.com/bnomei/kirby3-fingerprint/releases/tag/v3.0.5
