### ISSUE TITLE
Document passing attributes

### ISSUE THREAD

**Issue by yoanmalie** [bnomei/kirby3-fingerprint#17]
Hello,

I'm trying your (great!) plugin for a new website. And at first the debugger throw me an error because it's looked like I can't replace this line:
`<?= css('/assets/css/print.css', 'print') ?>`

By:
`<?= Bnomei\Fingerprint::css('/assets/css/print.css', 'print') ?>`

>Argument 3 passed to Bnomei\Fingerprint::helper() must be of the type array, string given, called in /Users/yoan/Projets/zardust/site/plugins/kirby3-fingerprint/classes/Fingerprint.php on line 218

By looking the error and the plugin code, I understand that the attributes need to be passed through an array. I think a common example with `media="print"` should be useful on the documentation 👍 

Thanks!

**Comment by bnomei** [comment]
ah. the kirby css helper does support a string with media as default. i did not know that.
https://getkirby.com/docs/reference/templates/helpers/css

also the js uses bool for async
https://getkirby.com/docs/reference/templates/helpers/js#example__async

i will see if i can get my helpers working more closely like the core. thanks!

**Comment by MaluNoPeleke** [comment]
I just tried the mentioned behaviour and found out that this is still not possible (talking about the async bool).
Can you add it to your plugin?

**Comment by bnomei** [comment]
@MaluNoPeleke as far as i can tell the 

```php
echo Bnomei\Fingerprint::css('/assets/css/style.css', ['async' => true, 'defer' => true, 'data-something' => 'my-value']);
```

should be working as expected.

**Comment by bnomei** [comment]
`<link async data-something="my-value" defer href="http://fingerprint.local:8080/assets/css/style.css" rel="stylesheet">`
