### ISSUE TITLE
File not found - server-side snippet doesn't work

### ISSUE THREAD

**Issue by S1SYPHOS** [bnomei/kirby3-fingerprint#19]
Hey there,
with my current setup, neither server-side snippet (I use the ones you provide in your README) works with this setup:

```php
// config.php
'bnomei.fingerprint.query' => false,

// head.php
echo Bnomei\Fingerprint::css($cssPath, ['integrity' => true]);
```

As for the code snippets needed for Apache/NGINX, I run the first in production, the last on my VM, neither works. The hash is generated, eg `main.dd22ee03e62b46ce2e6bd562c9f0cd4e.css`, and also the hash is applied to the `<link>` tag, but it doesn't work.

// Update:
The NGINX snippet works with 10 digit `filemtime` as hash, and so does this snippet for Apache: `RewriteRule ^(.+)\.([0-9]{10})\.(js|css)$ $1.$3 [L]` - it's the 32 digit-character string that doesn't ..

**Comment by bnomei** [comment]
thanks for finding the error in the readme 🙏
