### ISSUE TITLE
Include template related files

### ISSUE THREAD

**Issue by MaluNoPeleke** [bnomei/kirby3-fingerprint#28]
If I am on the 'blog' page and have a 'blog.css' file in the '/assets/css/templates/' folder this file will automatically be loaded by Kirby but cannot be cachebusted.
Can you add support for this?

**Comment by bnomei** [comment]
i am in parental leave right now. so probally i can not add anything soon.

maybe give https://github.com/johannschopplich/kirby-hashed-assets a try?

**Comment by bnomei** [comment]
does `@auto` as url not work?

https://github.com/bnomei/kirby3-fingerprint/blob/97144e21568b102a991c09178eb87fe53af22be4/classes/Fingerprint.php#L168

**Comment by MaluNoPeleke** [comment]
Yes, that works, didn't try, sorry and thanks.
Enjoy your time as a father!

**Comment by MaluNoPeleke** [comment]
Only downside of this is that it creates empty links if there is no specific css template to load.
