### ISSUE TITLE
Option https=>false does not work

### ISSUE THREAD

**Issue by abegehr** [bnomei/kirby3-fingerprint#31]
I'm applying https=false:
`<?= \Bnomei\Fingerprint::css('assets/css/index.css', ['https' => False]) ?>`
But this yields a link with `<link href="https://...` instead of `http`(without the s).

**Comment by bnomei** [comment]
hi @abegehr . sorry for the late reply. 

the kirby options have to be set globally in a config file not when using the function itself.

**site/config/config.php**
```php
<?php

return [
   'bnomei.fingerprint.https' => false,
    // other options...
];
```

**Comment by bnomei** [comment]
but i tired to make it a little bit easier for local setups by allowing http there even if https is forced.
https://github.com/bnomei/kirby3-fingerprint/commit/71120eaa4f3af10bbb416176cee60897db1aa551
