### ISSUE TITLE
`manifest.json` & renamed files

### ISSUE THREAD

**Issue by S1SYPHOS** [bnomei/kirby3-fingerprint#37]
Hey there,
I've been using @johannschopplich's `hashup` package, which renames to-be-revisioned files on the fly (which I really like), BUT inside `src/FingerprintFile.php`, we run into trouble since (inside `hash` function) we check if `$root` exists (well, using aforementioned approach it doesn't) and that's it.

This means we'd have to move the check right after `elseif (is_bool($query))`, since the manifest file will determine the file to use. What do you think?

While we're on it: `json_decode(F::read('path/to/file'))` could be shortened to `Json::read` ([docs](https://getkirby.com/docs/reference/objects/data/json/read)) :stuck_out_tongue:

**Comment by S1SYPHOS** [comment]
Hey there,
@bnomei are you there? Starting to worry about you! :smiling_face_with_tear:

**Comment by bnomei** [comment]
@S1SYPHOS 
hi martin,

sure if you can provide a PR i will merge that. i dont have the time to do it myself right now.

**Comment by S1SYPHOS** [comment]
Coming right up! 😜

**Comment by S1SYPHOS** [comment]
Should I make any changes or are you just very busy at the moment 😅
