### ISSUE TITLE
Plugin requirements

### ISSUE THREAD

**Issue by mynameisfreedom** [bnomei/kirby3-fingerprint#39]
Hi, @bnomei, I am using your great plugin in my [theme](https://www.thezero.club/demo/one/), and on 99,9% of server environments, it works great out of the box. 

But few users reported that it doesn't work. I know it won't work if mod_rewrite is not turned on, but the latest user with the issue claims his server has mod_rewrite on. What else could be the cause? What are plugin server requirements?

**Comment by bnomei** [comment]
maybe they have kirby in debug mode?
https://github.com/bnomei/kirby3-fingerprint#cache--performance

**Comment by bnomei** [comment]
sorry. debug mode should not matter for rendering the modified timestamp in the url.

**Comment by mynameisfreedom** [comment]
Probably, it is localhost. But, in my environment, it normally works even with debug mode turned on. 

But, I will tell him to try turning debug mode off.

**Comment by mynameisfreedom** [comment]
Just for the record, it is a Windows OS with XAMPP installed. Unfortunately, I cannot replicate, so I cannot test.

**Comment by mynameisfreedom** [comment]
Hi, @bnomei, the user found the solution. 

The plugin has https as a default, so cached URLs were on https, and the install on HTTP. So Windows saw it as a security issue, and didn't load cached scripts.

User added https://github.com/bnomei/kirby3-fingerprint#settings 'https' => false for your plugin in the config and the issue was resolved. 

So, I am closing this, issue resolved 👍

**Comment by bnomei** [comment]
thanks for letting me know
