### ISSUE TITLE
Not ready for multisite

### ISSUE THREAD

**Issue by jschopplich** [bnomei/kirby3-fingerprint#5]
First of all, your plugin works flawlessly. 
The plugin cache isn't ready for multisite environments though. When using it in production, visiting the first website (`.com` for example) generates the cache using its domain name. 

Fine so far.

However having the same site set up on a different domain (different home page etc.) the cache is called but returns absolute URLs to the first domain (`.com` for example), no URLs are generated to match the current domain. That's a problem.

Is there a way to detect use of different domain spaces? Like the config.php does with `config.multisite.com.php`?

**Comment by bnomei** [comment]
thanks for reporting this. should be fixed in v2.2.5

**Comment by jschopplich** [comment]
Nice. 👍
